swagger: "2.0"
info:
  title: "star-wars-api"
  version: "1.0.0"
schemes:
  - "https"
paths:
  /api/v1/health:
    get:
      operationId: "healthCheck"
      x-google-backend:
        address: 
        deadline: 60.0"SUA_URL_HEALTH_CHECK_AQUI"
      responses:
        200:
          description: "Success"

  /api/v1/people:
    get:
      operationId: "getPeople"
      x-google-backend:
        address: 
        deadline: 60.0"SUA_URL_GET_PEOPLE_AQUI"
      responses:
        200:
          description: "Success"
  /api/v1/people/{id}:
    get:
      operationId: "getPeopleById"
      parameters:
        - name: "id"
          in: "path"
          required: true
          type: "string"
      x-google-backend:
        address: 
        deadline: 60.0"SUA_URL_GET_PEOPLE_AQUI"
        path_translation: APPEND_PATH_TO_ADDRESS
      responses:
        200:
          description: "Success"

  /api/v1/films:
    get:
      operationId: "getFilms"
      x-google-backend:
        address: 
        deadline: 60.0"SUA_URL_GET_FILMS_AQUI"
      responses:
        200:
          description: "Success"
  /api/v1/films/{id}:
    get:
      operationId: "getFilmsById"
      parameters:
        - name: "id"
          in: "path"
          required: true
          type: "string"
      x-google-backend:
        address: 
        deadline: 60.0"SUA_URL_GET_FILMS_AQUI"
        path_translation: APPEND_PATH_TO_ADDRESS
      responses:
        200:
          description: "Success"

  /api/v1/planets:
    get:
      operationId: "getPlanets"
      x-google-backend:
        address: 
        deadline: 60.0"SUA_URL_GET_PLANETS_AQUI"
      responses:
        200:
          description: "Success"
  /api/v1/planets/{id}:
    get:
      operationId: "getPlanetsById"
      parameters:
        - name: "id"
          in: "path"
          required: true
          type: "string"
      x-google-backend:        
        address: 60.0"SUA_URL_GET_PLANETS_AQUI"
        path_translation: APPEND_PATH_TO_ADDRESS
      responses:
        200:
          description: "Success"

  /api/v1/starships:
    get:
      operationId: "getStarships"
      x-google-backend:
        address: 
        deadline: 60.0"SUA_URL_GET_STARSHIPS_AQUI"
      responses:
        200:
          description: "Success"
  /api/v1/starships/{id}:
    get:
      operationId: "getStarshipsById"
      parameters:
        - name: "id"
          in: "path"
          required: true
          type: "string"
      x-google-backend:
        address: 
        deadline: 60.0"SUA_URL_GET_STARSHIPS_AQUI"
        path_translation: APPEND_PATH_TO_ADDRESS
      responses:
        200:
          description: "Success"

  /api/v1/vehicles:
    get:
      operationId: "getVehicles"
      x-google-backend:
        address: 
        deadline: 60.0"SUA_URL_GET_VEHICLES_AQUI"
      responses:
        200:
          description: "Success"
  /api/v1/vehicles/{id}:
    get:
      operationId: "getVehiclesById"
      parameters:
        - name: "id"
          in: "path"
          required: true
          type: "string"
      x-google-backend :       
        address: 60.0"SUA_URL_GET_VEHICLES_AQUI"
        path_translation: APPEND_PATH_TO_ADDRESS
      responses:
        200:
          description: "Success"
